package ru.spbu.project.models;

/**
 * Класс ENUM, который отслеживает на какой стадии находится сотрудник
 */
public enum Stage {
  WAITING_APPLICATION_TRAINING,
  REFUSAL_APPLICATION,
  PASSES_ENTRANCE_TEST,
  FAILED_ENTRANCE_TEST,
  PASSED_ENTRANCE_TEST,
  MODULE_1,
  MODULE_2,
  MODULE_3,
  MODULE_4,
  MODULE_5,
  MODULE_6,
  MODULE_7,
  MODULE_8,
  PRACTICE_TASK_1,
  PRACTICE_TASK_2,
  EXPECTS_PRODUCTION_PRACTICE,
  PRODUCTION_PRACTICE,
  EXAM,
  FAILED_EXAM,
  PASSED_EXAM
}
